# Generated by Django 4.2.1 on 2023-07-02 22:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', ckeditor.fields.RichTextField(verbose_name='Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='enterprise/logo/', verbose_name='Logo')),
                ('provincia', models.CharField(max_length=250, verbose_name='Provincia')),
                ('municipio', models.CharField(max_length=250, verbose_name='Municipio')),
                ('tipo', models.CharField(max_length=250, verbose_name='Tipo')),
                ('actividad', models.CharField(max_length=250, verbose_name='Actividad')),
                ('representante', models.CharField(max_length=250, verbose_name='Representante')),
                ('telefono', models.CharField(max_length=250, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=250, verbose_name='Teléfono')),
                ('fecha_aprobacion', models.DateField(verbose_name='Fecha de aprovación')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aprobado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'ordering': ('is_active',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=250, verbose_name='Servicio')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='main.enterprise')),
            ],
            options={
                'verbose_name': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.URLField(verbose_name='Enlace')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='main.enterprise')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='publicidad/thumbnail/', verbose_name='Thumbnail')),
                ('image', models.ImageField(upload_to='publicidad/imagen/', verbose_name='Imagen')),
                ('link', models.URLField(verbose_name='Link')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicidades', to='main.enterprise')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
            },
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField(verbose_name='Enlace')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='main.enterprise')),
            ],
            options={
                'verbose_name': 'Enlace',
            },
        ),
    ]
