# Generated by Django 4.2.1 on 2023-07-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de aprovación'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='nombre',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre'),
        ),
        migrations.RemoveField(
            model_name='sector',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='sector',
            name='enterprise',
            field=models.ManyToManyField(related_name='sectores', to='main.enterprise'),
        ),
    ]
