# Generated by Django 4.2.1 on 2023-07-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_municipio_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='correo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Correo'),
        ),
    ]
