# Generated by Django 4.2.1 on 2023-07-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_enterprise_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicidadGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='publicidad/thumbnail/', verbose_name='Thumbnail')),
                ('image', models.ImageField(upload_to='publicidad/imagen/', verbose_name='Imagen')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Publicidad general',
                'verbose_name_plural': 'Publicidades generales',
            },
        ),
    ]
