# Generated by Django 4.2.1 on 2023-07-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sector_enterprise_enterprise_sectores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='sectores',
            field=models.ManyToManyField(blank=True, null=True, related_name='sectores', to='main.sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
