# Generated by Django 4.2.1 on 2023-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_publicidadgeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Configuración',
            },
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ('nombre',)},
        ),
    ]
