# Generated by Django 4.2.1 on 2023-07-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_enterprise_sectores_alter_sector_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='nombre',
            field=models.CharField(default='link', max_length=250, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
