# Generated by Django 4.2.1 on 2023-07-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_enlace_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre'),
        ),
    ]
