# Generated by Django 4.2.1 on 2023-07-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_publicidad_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='image',
            field=models.ImageField(help_text='Relación aspecto: Cuadrada', upload_to='publicidad/imagen/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='publicidadgeneral',
            name='image',
            field=models.ImageField(help_text='Relación aspecto: Vertical', upload_to='publicidad/imagen/', verbose_name='Imagen'),
        ),
    ]
