# Generated by Django 4.2.1 on 2023-07-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_provincia_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre'),
        ),
    ]
