# Generated by Django 4.2.1 on 2023-07-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_enterprise_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='provincia',
        ),
    ]
